import React from 'react';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';
import { faLightbulb} from '@fortawesome/free-solid-svg-icons';
import './Questions.css'

export default function Questions() {
    return (
        <section id='questions'>
            {/* <div className="blog">
                <div className="container">
                    <div className="row text-center">
                        <div className="col-lg-12"> */}
            <div className="questions">
                <div className="container">
                    <div className="row align-items-center">
                        <div className="col-12 text-center">
                            <h2 className="blog__title">Frequently Asked Questions</h2>
                            <div className="section-title-border"></div>
                            <p className="blog__subtitle">Here for your convenience we have listed down some important questions and their answers that you might want to know about how the features of this website work.</p>
                        </div>

                <div className="col-lg-6 col-12 mt-2">
              <h5>
               <FontAwesomeIcon icon={faLightbulb} style={{ color: "#FAB005", marginRight: "0.5em" }} />
                How does this sentiment analysis work?{" "}
              </h5>

              <p className="ms-4">
              It processes the url you provide and identifies sentiments associated with specific aspects. It breaks down overall sentiment into positive, neutral, or negative opinions.
              </p>

              <h5>
                <FontAwesomeIcon icon={faLightbulb} style={{ color: "#FAB005", marginRight: "0.5em" }} />
                Can I trust the sentiment scores generated by this website?{" "}
              </h5>

              <p className="ms-4">
              Absolutely! Our sentiment analysis model is trained on a large dataset. While no system is perfect, we continuously improve our algorithms to provide reliable results.
              </p>

              <h5> 
                <FontAwesomeIcon icon={faLightbulb} style={{ color: "#FAB005", marginRight: "0.5em" }} />
                How can I use the sentiment scores for decision-making?{" "}
              </h5>

              <p className="ms-4">
              The sentiment scores help you understand customer perceptions. Use them to identify areas for improvement and prioritize feature enhancements based on positive aspects.
              </p>

            </div>

            <div className="col-lg-6 col-12 mt-2">
            <h5> 
                <FontAwesomeIcon icon={faLightbulb} style={{ color: "#FAB005", marginRight: "0.5em" }} />
                Is this sentiment analysis suitable for all types of products?{" "}
              </h5>

              <p className="ms-4">
              Right now it will only work for electronic items, submit the urk of any electronic item and it's sentiment score will be generated.
              </p>

              <h5> 
                <FontAwesomeIcon icon={faLightbulb} style={{ color: "#FAB005", marginRight: "0.5em" }} />
                What if my product has multiple aspects?{" "}
              </h5>

              <p className="ms-4">
              No worries! Our system dissects sentiments for each aspect separately. You’ll receive granular insights, allowing you to address specific pain points.
              </p>

              <h5>
                <FontAwesomeIcon icon={faLightbulb} style={{ color: "#FAB005", marginRight: "0.5em" }} />
                How do I interpret the sentiment scores?{" "}
              </h5>

              <p className="ms-4">
              Positive scores indicate favorable sentiments, negative scores highlight areas for improvement, and neutral scores represent neutrality. Dive into the details to make informed decisions!
              </p>

            </div>
        </div>
    </div>
</div>
    </section>
    );
}